[relaychain]
default_image = "parity/polkadot:latest"
default_command = "./bin/polkadot"
chain = "westend-local"

[[relaychain.nodes]]
name = "alice"
validator = true
ws_port = 42069
# args = [
#     "-lparachain=debug,xcm::process-message=trace,xcm::execute=trace,xcm::process=trace",
# ]

[[relaychain.nodes]]
name = "bob"
validator = true
# args = [
#     "-lparachain=debug,xcm::process-message=trace,xcm::execute=trace,xcm::process=trace",
# ]

[[parachains]]
id = 1000
cumulus_based = true
chain = "asset-hub-westend-local"

# run charlie as parachain collator
[[parachains.collators]]
name = "charlie"
validator = true
image = "parity/polkadot-parachain:latest"
command = "./bin/polkadot-parachain"
args = [
    "--force-authoring",
    "-lparachain=debug,xcm::process-message=trace,xcm::execute=trace,xcm::process=trace",
]
ws_port = 42070
