import type { ChainId, Token, TokenIdsPair } from "@kheopswap/registry";
import type { SS58String } from "polkadot-api";

/**
 * Directory data types for runtime consumption.
 * These match the JSON schema generated by directory/src/types.ts
 *
 * IMPORTANT: There are NO imports from the directory package at runtime.
 * The directory JSON files are fetched from GitHub and cast to these types.
 * This ensures directory updates don't trigger Cloudflare rebuilds.
 */

export type DirectoryToken = Token;

export type DirectoryPool = {
	type: "asset-convertion";
	chainId: ChainId;
	poolAssetId: number;
	tokenIds: TokenIdsPair;
	owner: SS58String;
};

export type DirectoryChainData = {
	chainId: ChainId;
	generatedAt: string;
	tokens: DirectoryToken[];
	pools: DirectoryPool[];
};

export type DirectoryLoadingState = "loading" | "loaded" | "error";

export type DirectoryState = {
	status: DirectoryLoadingState;
	data: DirectoryChainData | null;
	error: string | null;
	lastUpdated: number | null;
};
